import {
    ResponsiveContainer,
    LineChart,
    Line,
    CartesianGrid,
    XAxis,
    YAxis,
    Tooltip
} from "recharts";

export default function PlantationChart({

    dashboard = [],

    summary = {}

}) {

    const chartData = dashboard

        .slice(0, 10)

        .map((ward, index) => ({

            name:

                ward.ward_name ||

                ward.Ward_Name ||

                `Ward ${index + 1}`,

            score:

                Number(

                    ward.Composite_Score ??

                    ward.score ??

                    ward.Impact_Mean ??

                    0

                )

        }));

    return (

        <div

            style={{

                background: "#131d2f",

                borderRadius: "24px",

                padding: "25px",

                height: "360px",

                border: "1px solid rgba(255,255,255,.05)"

            }}

        >

            <h2

                style={{

                    color: "white",

                    marginBottom: "8px"

                }}

            >

                Top 10 Ward Impact Scores

            </h2>

            <p

                style={{

                    color: "#94a3b8",

                    marginBottom: "25px"

                }}

            >

                Generated by CanopyAI Recommendation Engine

            </p>

            <ResponsiveContainer

                width="100%"

                height="80%"

            >

                <LineChart

                    data={chartData}

                >

                    <CartesianGrid

                        stroke="#334155"

                    />

                    <XAxis

                        dataKey="name"

                        stroke="#94a3b8"

                    />

                    <YAxis

                        stroke="#94a3b8"

                    />

                    <Tooltip />

                    <Line

                        type="monotone"

                        dataKey="score"

                        stroke="#22c55e"

                        strokeWidth={3}

                    />

                </LineChart>

            </ResponsiveContainer>

        </div>

    );

}